### ISSUE TITLE
bazelbuild/examples indexing problem

### ISSUE THREAD

**Issue by tpasternak** [JetBrains/bazel-bsp#14]
Scenario:
1. Import `java-tutorial` from https://github.com/bazelbuild/examples
2. Open `Greeting.java`

Observed: 
`Greeting.java` is not correctly indexed - package name is marked as incorrect

**Comment by andrefmrocha** [comment]
Thanks for noticing this! It would seem that this problem also affects our current development build of the server, which uses the same pathing. 

Probably this should be looked into. Our heuristic for calculating roots seems to be correct, but the behavior is not as expected. I believe that the problem might be associated with the the value `baseDirectory` on each target, since it is pointing directly towards the folder where the source files are. My assumption is this since IntelliJ suggestion to move to the correct folder creates the whole package structure within that folder.  

@jastice did anything change on your side for this?

**Comment by jastice** [comment]
Nothing really changed in the BSP support. Maybe there's some interaction with the [enhanced package prefixes](https://blog.jetbrains.com/scala/2020/11/26/enhanced-package-prefixes/) in 2020.3? I haven't looked into this yet.

**Comment by andrefmrocha** [comment]
Just tried to importing this through 2020.2 and found that this did not happen there. Going to close this and open an issue on youtrack about it. You can find it [here](https://youtrack.jetbrains.com/issue/SCL-18551)
