### ISSUE TITLE
workspace context

### ISSUE THREAD

**Issue by abrams27** [JetBrains/bazel-bsp#158]
I think that it would be nice to have a `workspace context` (temporary name) to keep all information about the workspace - targets, path to root, bazelrunner all information needed during server lifetime

also, this would be very useful in terms project view usage, I think that project view should be mapped into workspece context, since project view might contain redundant information - for example we don't need java path used during initialisation or debugger address. Also, it might be useful during `derive_targets_from_directories` implementation - targets inside workspace context would be deducted on provided targets / directories + `derive_targets_from_directories` flag

**Comment by lukaszwawrzyk** [comment]
It sounds useful. I plan to have something similar, maybe a bit smaller in scope though. I have a very early version of such thing. It is Project together with ProjectStorage. I want to be able to ask ProjectStorage for Project instance at any point. The Project would essentially contain all information from sync (output from aspect(s?)). Currently it contains the resolved targets that should be imported as well as TargetInfo for each target.
I would like it to contain proper project structure like modules with all relevant attributes like sources, dependencies, SDKs.
The idea is that workspaceBuildTargets triggers a sync, which calls bazel and builds the project from the beginning, and then stores it in the ProjectStorage. Then, any other endpoint (including workspaceBuildTargets) can ask ProjectStorage for Project, map its contents to BSP protocol classes and send the response. 
ProjectStorage should also save the project to disk in some format and be able to read it later, so that when server is restarted it doesn't need to sync again to work. We may also consider storing some metadata to support incremental sync.
