### ISSUE TITLE
Installer does not print the installation location

### ISSUE THREAD

**Issue by agluszak** [JetBrains/bazel-bsp#48]
When you run `java -cp "$bsp_path" org.jetbrains.bsp.bazel.install.Install` the installer prints `Bazel BSP server installed in`, but there is no location provided

**Comment by Abrams27** [comment]
In general, it was caused by multiple ways of installing bsp: installation in place (default one) and via `Install` command line arguments. I would prefer the first one. 

Btw, second mechanism allows also setting other parameters like java, bazel or debugger -- imo it will be deprecated now, when the ProjectView mechanizm was introduced.

further changes will be done here: https://github.com/JetBrains/bazel-bsp/issues/77
