### ISSUE TITLE
Check if generated sources are properly picked up

### ISSUE THREAD

**Issue by andrefmrocha** [JetBrains/bazel-bsp#8]
There are several mentions as to how generated sources exist within bazel scope, but I haven't been able to find any real example of them to test it against my solution. A workspace with generated sources should be found and properly tested against

**Comment by lukaszwawrzyk** [comment]
Check this minimal project with java and thrift. 
https://github.com/VirtusLab/intellij-pants-plugin-tests/tree/master/tests/src/test/resources/projects/BazelExample 
Thrift files are generated and used in tests of java_hello. The class is correctly recognized and when user navigates to it, it goes to decompiled class file instead of sources.

**Comment by abrams27** [comment]
still doesn't work after https://github.com/JetBrains/bazel-bsp/pull/147

there is similar issue for photo files as well (not always): example project https://github.com/liucijus/rules-scala-proto-toolchain/ from https://github.com/JetBrains/bazel-bsp/issues/127
